apiVersion: v1
kind: Pod
metadata:
  name: grafana
  namespace: monitoring
  labels:
    app: grafana
spec:
  containers:
  - name: grafana
    image: grafana/grafana:10.0.1
    ports:
      - containerPort: 3000
    env:
      - name: GF_SECURITY_ADMIN_USER
        value: admin
      - name: GF_SECURITY_ADMIN_PASSWORD
        value: admin123
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: monitoring
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
